public enum State
{
    START,
    CHARACTER,
    INTEGER_NO_EXP, INTEGER_UNSIGNED_EXP_START, INTEGER_UNSIGNED_EXP_F, INTEGER_SIGNED_EXP_START, INTEGER_SIGNED_EXP_F,
    FLOAT_NO_EXP, FLOAT_UNSIGNED_EXP_START, FLOAT_UNSIGNED_EXP_F, FLOAT_SIGNED_EXP_START, FLOAT_SIGNED_EXP_F,
    PLUS, MINUS, TIMES, DIV,
    ASSIGN, EQ, LE, LT, GE, GT, BANG, NE,
    SEMI, COMMA, LP, RP, LB, RB, LBR, RBR,
    LINE_COMMENT, BLOCK_COMMENT,
    SYMBOL,
    ERROR,
    FINAL;
}